### ISSUE TITLE
Strange behaviour for points near the origin

### ISSUE THREAD

**Issue by stelmo** [JeffreySarnoff/AngleBetweenVectors.jl#2]
Hi, I noticed that `angle` does not actually do as claimed in the docstrings: 
```julia
help?> angle
...
If one of the points is at the origin, the result is zero.
...
```
Specifically:
```julia
julia> angle((0.0, 0.0), (1.0, 1.0))
NaN
```
Also, there is some inconsistent behaviour near the origin:
```julia
julia> angle((0.0, 0.001), (1.0, 1.0))
0.7853981633974483

julia> angle((0.001, 0.001), (1.0, 1.0))
1.5700924586837754e-16

julia> angle((0.0001, 0.001), (1.0, 1.0))
0.6857295109062864

julia> angle((0.0001, 0.0001), (1.0, 1.0))
1.5700924586837754e-16
```
I would expect all of the above to be approximately `0.7853981633974483`?

I am using `[ec570357] AngleBetweenVectors v0.3.0`.

**Comment by SteffenPL** [comment]
> I would expect all of the above to be approximately 0.7853981633974483?

For me, the behaviour of the package in the four cases near origin makes sense. The angle doesn't depend on the length of the vector, hence
```
angle((0.0, 0.001), (1.0, 1.0))   
≈ angle((0.0, 1.0), (1.0, 1.0))     
≈ π/4
```
```
angle((0.001, 0.001), (1.0, 1.0))   
≈ angle((0.0001, 0.0001), (1.0, 1.0))   
≈ angle((1.0, 1.0), (1.0, 1.0))    
≈ 0.0
```

```
angle((0.0001, 0.001), (1.0, 1.0))   
≈ angle((0.1, 1.0), (1.0, 1.0))     
# ≈ some number less than  π/4
```

**Comment by JeffreySarnoff** [comment]
I like that angle((0.0, 0.0), _) is NaN, as that is no angle, it is an oriented vector.
@SteffenPL  thank you -- your logic gets in
