### ISSUE TITLE
replace unitize by scaling to same magnitude

### ISSUE THREAD

**Issue by bgodard** [JeffreySarnoff/AngleBetweenVectors.jl#4]
Maybe I am totally wrong but could this code be even better without divisions: 
```julia
     
    n1 = norm(point1)
    n2 = norm(point2)

    p1 = n2 * point1
    p2 = n1 * point2

    # p1 and p2 have now same magnitudes

    y = p1 .- p2
    x = p1 .+ p2

    a = 2 * atan(norm(y) , norm(x))  # use atan2(Y,X) result already in [0,pi]
```

**Comment by JeffreySarnoff** [comment]
Certainly faster, slightly less accurate in this case:
p1 = (3.0, 5.0, 7.0)
p2 = (7.0, 19.0, 22.0)
relerror about 4x using BigFloat and compared to angle(_,_)
I need to test this on more values, though (the speedup is nice).

**Comment by JeffreySarnoff** [comment]
either way using atan2 is the way to go (thank you)

**Comment by JeffreySarnoff** [comment]
I do like that it is faster, and almost as accurate.  That is a reasonable use case.
I may add this to the docs, when there are docs.  You get the credit.
